t,f=avgFreqDB(longueur=0.1485,commentaire="var longueur")
plt.plot(t,f,label="0.1485")
t,f=avgFreqDB(longueur=0.21,commentaire="var longueur")
plt.plot(t,f,label="0.21")
t,f=avgFreqDB(longueur=0.297,commentaire="var longueur")
plt.plot(t,f,label="0.297")
plt.legend()
plt.show()
