plotFreq("res/freq/0129e/")
plotFreq("res/freq/0129a/")
plt.title("diamètre 2mm")
plt.ylabel("Frequency")
plt.xlabel("Time")
plt.xlim(0,60)
plt.ylim(0,1)
plt.show()
plt.figure()
plotFreq("res/freq/0129/")
plotFreq("res/freq/0129f/")
plt.title("diamètre 5mm")
plt.ylabel("Frequency")
plt.xlabel("Time")
plt.xlim(0,60)
plt.ylim(0,1)
plt.show()
